version: '3'
services:
  database:
    build: ../db
    restart: always
    ports:
      - "5432"
  application:
    build: ../app
    ports:
      - "5000:6000"
    depends_on:
      - "database"
    command: ["python", "app.py"]
  frontend:
    build: ../web
    ports:
      - "80:80"
    depends_on:
      - "application"
